### PR TITLE
close #30 PanicログとErrorログにstacktraceをのせる

### LINKED ISSUE #30: ログにbacktraceを載せたい

### PR DESCRIPTION
**Pull request by h3poteto**

### CODE REVIEW

File: modules/logging/logging.go [hunk 1]
```diff
@@ -35,9 +37,21 @@ func SharedInstance() *LogStruct {
 	return sharedInstance
 }
 
-func (u *LogStruct) MethodInfo(model string, method string) *logrus.Entry {
-	return u.log.WithFields(logrus.Fields{
-		"model":  model,
-		"method": method,
-	})
+func (u *LogStruct) MethodInfo(model string, method string, stack ...bool) *logrus.Entry {
```
Comment (h3poteto) [inline modules/logging/logging.go]: __[golint]__
* [golint] exported method LogStruct.MethodInfo should have comment or be unexported

File: modules/logging/logging.go [hunk 2]
```diff
@@ -35,9 +37,21 @@ func SharedInstance() *LogStruct {
...
+	if len(stack) > 0 && stack[0] {
+		buf := make([]byte, 1<<16)
+		runtime.Stack(buf, false)
+		return u.log.WithFields(logrus.Fields{
+			"time":       time.Now(),
+			"model":      model,
+			"method":     method,
+			"stacktrace": string(buf),
+		})
+	} else {
```
Comment (h3poteto) [inline modules/logging/logging.go]: __[golint]__
* [golint] if block ends with a return statement, so drop this else and outdent its block

File: modules/logging/logging.go [hunk 3]
```diff
@@ -35,8 +37,19 @@ func SharedInstance() *LogStruct {
 	return sharedInstance
 }
 
-func (u *LogStruct) MethodInfo(model string, method string) *logrus.Entry {
+func (u *LogStruct) MethodInfo(model string, method string, stack ...bool) *logrus.Entry {
```
Comment (h3poteto) [inline modules/logging/logging.go]: __[golint]__
* [golint] exported method LogStruct.MethodInfo should have comment or be unexported
